[build]
builder = "nixpacks"

[deploy]
startCommand = "Set-Location PORT; npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[build.buildCommand]
command = "Set-Location PORT; npm install; npm run build"
