[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[build.buildCommand]
command = "cd PORT && npm install && npm run build"
